package e2e

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// Result is one marked run.
type Result struct {
	Scenario Scenario
	Attempt  int
	Outcome  Outcome
	Score    Score
}

// Report renders docs/agent-eval.md from a set of marked runs.
//
// The trajectories are the point rather than an appendix. "Wrong" and "wrong,
// but it queried the right metric at step 3 and misread it" are different
// problems, and only the second says what to change — so every run's steps are
// printed, correct ones included.
func Report(results []Result, budget Budget, model string, when time.Time) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Agent Evaluation\n\n")
	fmt.Fprintf(&b, "Generated by `make agent-eval` on %s.\n\n", when.UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "Model `%s`, budget %d steps / %d tool calls. "+
		"Every scenario presents as \"checkout requests are bad\"; they differ only in why. "+
		"Scoring is deterministic — see `docs/plans/agent-evaluation.md` for the rule and for "+
		"what it understates.\n\n", model, budget.MaxSteps, budget.MaxToolCalls)

	byScenario := groupByScenario(results)
	names := scenarioOrder(results)

	correct, total := 0, len(results)
	for _, r := range results {
		if r.Score.Correct {
			correct++
		}
	}

	fmt.Fprintf(&b, "## Accuracy\n\n")
	fmt.Fprintf(&b, "**%d of %d runs correct (%s).**\n\n", correct, total, pct(correct, total))
	fmt.Fprintf(&b, "| Scenario | Correct | Right service | Stop reason | Steps | Tool calls | Tokens | Seconds |\n")
	fmt.Fprintf(&b, "| --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for _, name := range names {
		rs := byScenario[name]
		ok, svc := 0, 0
		for _, r := range rs {
			if r.Score.Correct {
				ok++
			}
			if r.Score.ServiceOK {
				svc++
			}
		}
		fmt.Fprintf(&b, "| `%s` | %d/%d | %d/%d | %s | %s | %s | %s | %s |\n",
			name, ok, len(rs), svc, len(rs),
			joinStrings(collect(rs, func(r Result) string { return r.Outcome.StopReason })),
			spread(collect(rs, func(r Result) string { return itoa(r.Outcome.StepCount) })),
			spread(collect(rs, func(r Result) string { return itoa(r.Outcome.ToolCallCount) })),
			spread(collect(rs, func(r Result) string {
				return itoa(r.Outcome.PromptTokens + r.Outcome.CompletionTokens)
			})),
			spread(collect(rs, func(r Result) string {
				return itoa(int(r.Outcome.Elapsed.Round(time.Second).Seconds()))
			})))
	}

	fmt.Fprintf(&b, "\nDistributions are the values of the individual runs, not a mean: "+
		"with three runs a mean hides whether the agent is stably right, stably wrong, or "+
		"flipping a coin.\n")

	writeBudget(&b, results, budget)

	fmt.Fprintf(&b, "\n## What went wrong\n\n")
	wrong := 0
	for _, name := range names {
		for _, r := range byScenario[name] {
			if r.Score.Correct {
				continue
			}
			wrong++
			fmt.Fprintf(&b, "- **`%s` run %d** — %s\n", name, r.Attempt, r.Score.Why)
		}
	}
	if wrong == 0 {
		fmt.Fprintf(&b, "Nothing. Every run was marked correct.\n")
	}

	fmt.Fprintf(&b, "\n## Trajectories\n\n")
	for _, name := range names {
		rs := byScenario[name]
		fmt.Fprintf(&b, "### `%s`\n\n", name)
		fmt.Fprintf(&b, "Expected: %s\n\n", expectationLine(rs[0].Scenario))
		for _, r := range rs {
			writeTrajectory(&b, r)
		}
	}
	return b.String()
}

// Budget is what the runs were given, recorded so the numbers can be read
// against it.
type Budget struct {
	MaxSteps     int
	MaxToolCalls int
}

// Run is a whole evaluation, saved next to its report.
//
// It exists so that a change to the scoring can be re-applied without paying
// for the investigations again: the marks are a pure function of the outcomes,
// and the outcomes are what cost money.
type Run struct {
	Results []Result  `json:"results"`
	Budget  Budget    `json:"budget"`
	Model   string    `json:"model"`
	When    time.Time `json:"when"`
}

// writeBudget reports how the runs spent what they were given.
//
// It is here rather than in the prose because it is the thing most likely to
// change between evaluations and least likely to be re-read carefully: a run
// that never chooses to finish is giving its forced diagnosis, not its
// considered one.
func writeBudget(b *strings.Builder, results []Result, budget Budget) {
	var bounded, failed, refused, calls, retrievals int
	for _, r := range results {
		switch {
		case r.Outcome.Status != "SUCCEEDED":
			failed++
		case r.Outcome.StopReason != "COMPLETED":
			bounded++
		}
		for _, s := range r.Outcome.Steps {
			switch s.ActionType {
			case "retrieve":
				retrievals++
			case "tool_call":
				calls++
				if s.ToolStatus != "" && s.ToolStatus != "OK" {
					refused++
				}
			}
		}
	}
	voluntary := len(results) - bounded - failed

	fmt.Fprintf(b, "\n## Where the budget went\n\n")
	fmt.Fprintf(b, "- **%d of %d runs stopped at a bound** rather than calling `finish` on "+
		"their own; %d finished voluntarily and %d never produced a diagnosis. A bounded run "+
		"gives its forced diagnosis, not its considered one, so the accuracy above is a "+
		"lower bound on what a larger budget would give.\n",
		bounded, len(results), voluntary, failed)
	fmt.Fprintf(b, "- **%d retrieval steps and %d tool calls**, of which %d did not return OK. "+
		"A refused call still spends budget, so the trajectories are worth reading for what "+
		"was being asked.\n", retrievals, calls, refused)
	fmt.Fprintf(b, "- The budget was %d steps and %d tool calls, above the shipped default of "+
		"8 and 6; `docs/plans/end-to-end-test.md` says why.\n",
		budget.MaxSteps, budget.MaxToolCalls)
}

func writeTrajectory(b *strings.Builder, r Result) {
	mark := "wrong"
	if r.Score.Correct {
		mark = "correct"
	}
	fmt.Fprintf(b, "**Run %d — %s** (`%s`/`%s`, %d steps, %d tool calls, %d tokens, %s)\n\n",
		r.Attempt, mark, r.Outcome.Status, r.Outcome.StopReason,
		r.Outcome.StepCount, r.Outcome.ToolCallCount,
		r.Outcome.PromptTokens+r.Outcome.CompletionTokens,
		r.Outcome.Elapsed.Round(time.Second))

	fmt.Fprintf(b, "| Step | Action | Tool | Status |\n| --- | --- | --- | --- |\n")
	for _, s := range r.Outcome.Steps {
		status := s.Status
		if s.ToolStatus != "" && s.ToolStatus != s.Status {
			status = s.Status + " / " + s.ToolStatus
		}
		fmt.Fprintf(b, "| %d | %s | `%s` | %s |\n", s.Number, s.ActionType, s.Tool, status)
	}

	fmt.Fprintf(b, "\n> **%s** — %s\n\n", serviceOrNone(r.Outcome.AffectedService),
		oneParagraph(r.Outcome.RootCause))
	if !r.Score.Correct {
		fmt.Fprintf(b, "Marked wrong: %s\n\n", r.Score.Why)
	}
}

// expectationLine renders a scenario's expectation in the terms it is marked
// by, so that a reader can disagree with the mark rather than only with the
// diagnosis.
func expectationLine(s Scenario) string {
	if s.Expect.Healthy {
		return "nothing is wrong; a diagnosis naming " +
			joinQuoted(s.Expect.Not) + " is an invented root cause"
	}
	var parts []string
	parts = append(parts, "`"+s.Expect.Service+"`")
	for _, group := range s.Expect.Any {
		parts = append(parts, "one of "+joinQuoted(group))
	}
	if len(s.Expect.Not) > 0 {
		parts = append(parts, "and none of "+joinQuoted(s.Expect.Not))
	}
	return strings.Join(parts, ", ")
}

func groupByScenario(results []Result) map[string][]Result {
	out := map[string][]Result{}
	for _, r := range results {
		out[r.Scenario.Name] = append(out[r.Scenario.Name], r)
	}
	for _, rs := range out {
		sort.Slice(rs, func(i, j int) bool { return rs[i].Attempt < rs[j].Attempt })
	}
	return out
}

// scenarioOrder keeps the order the runs were made in, which is the order
// EvalScenarios declares.
func scenarioOrder(results []Result) []string {
	seen := map[string]bool{}
	var out []string
	for _, r := range results {
		if !seen[r.Scenario.Name] {
			seen[r.Scenario.Name] = true
			out = append(out, r.Scenario.Name)
		}
	}
	return out
}

func collect(rs []Result, f func(Result) string) []string {
	out := make([]string, 0, len(rs))
	for _, r := range rs {
		out = append(out, f(r))
	}
	return out
}

// spread renders the individual values, collapsing them when they agree.
func spread(values []string) string {
	all := true
	for _, v := range values {
		if v != values[0] {
			all = false
			break
		}
	}
	if all {
		return values[0]
	}
	return strings.Join(values, " / ")
}

// joinStrings renders distinct values, in first-seen order.
func joinStrings(values []string) string {
	seen := map[string]bool{}
	var out []string
	for _, v := range values {
		if !seen[v] {
			seen[v] = true
			out = append(out, v)
		}
	}
	return strings.Join(out, " / ")
}

func joinQuoted(terms []string) string {
	out := make([]string, 0, len(terms))
	for _, t := range terms {
		out = append(out, "`"+t+"`")
	}
	return strings.Join(out, ", ")
}

func pct(n, total int) string {
	if total == 0 {
		return "0%"
	}
	return fmt.Sprintf("%.0f%%", 100*float64(n)/float64(total))
}

func itoa(n int) string { return fmt.Sprintf("%d", n) }

func serviceOrNone(s string) string {
	if strings.TrimSpace(s) == "" {
		return "(no service named)"
	}
	return s
}

// oneParagraph flattens a diagnosis onto one line so a markdown blockquote
// stays a blockquote.
func oneParagraph(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	return strings.Join(strings.Fields(s), " ")
}
